//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiosco_Don_Pepe
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleTicket
    {
        public int IdDetalle { get; set; }
        public int IdTicket { get; set; }
        public int IdProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
