//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiosco_Don_Pepe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaFacturacionEntities : DbContext
    {
        public SistemaFacturacionEntities()
            : base("name=SistemaFacturacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetalleTicket> DetalleTickets { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
